[build-system]
requires = ["setuptools>=58", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fastpdi_dpp"
description = "FastPDI Data Processing Pipeline"
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "Miles Lucas", email = "mdlucas@hawaii.edu"}]
requires-python = ">=3.10"
dependencies = [
    "astropy>=4,<6",
    "astroquery>=0.4,<0.5",
    "astroscrappy>=1,<2",
    "numpy>=1.16,<2",
    "opencv-python>=4,<5",
    "pandas>=1.2,<2",
    "photutils>=1,<2",
    "pyserde>=0.9,<0.10",
    "scikit-image>=0.18,<0.20",
    "scipy>=1.7,<2",
    "tomli>=2,<3",
    "tomli-w>=1,<2",
    "tqdm==4.*",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "autoflake==2",
    "black==22.*",
    "isort==5.10.*"
]
test = [
    "pytest==7.*",
    "pytest-cov==3.*",
    "pytest-randomly==3.*",
    "black==22.*",
    "pytest-black==0.3.*",
]
docs = [
    "numpy<1.19",
    "proplot",
    "sphinx>=4.5,<5",
    "myst_nb==0.13",
    "sphinx_book_theme==0.3",
    "zenodo-get>=1.3,<2"
]

[project.scripts]
fpp = "fastpdi_dpp.cli.fpp:main"

[tool.setuptools.dynamic]
version = {attr = "fastpdi_dpp.__version__"}

[tool.pytest.ini_options]
log_cli = false
log_cli_level = "DEBUG"
log_cli_format = "[%(levelname)s] (%(name)-15s) %(message)s"
addopts = "--randomly-seed=4796"

[tool.coverage.run]
source = ["fastpdi_dpp"]

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
multi_line_output = 3